### ISSUE TITLE
qos

### ISSUE THREAD

**Issue by schaefer01** [PaoloSarti/NATS.jl#1]
Hi,
  I can't figure out how to set qos. Behavior appears to be qos=2, but what if lossy is ok, and I want qos=1?

**Comment by PaoloSarti** [comment]
Hi,
This library implements the [NATS Client Protocol](https://docs.nats.io/reference/reference-protocols/nats-protocol), which doesn't mention QoS. The library itself internally uses native Julia channels in which commands and messages are stored even if you don't consume them right away so it has some QoS built in client side.

Do you mean the qos for Mqtt clients? That protocol is not supported here but you might want to take a look at [MQTT.jl](https://github.com/rweilbacher/MQTT.jl), to use that protocol instead of the native NATS protocol.

**Comment by schaefer01** [comment]
you are right, my mistake
